# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79a25080393bf33117601b3787b5c3811bb0f99297a91039a7d7fbcb9c4c1b252a5dd5a9922b268bdd3247ca50d3d9ba648aadaeb81d2a1cee3d4185822f1768

test:
  secret_key_base: 0df1e07768d892f46e1c9593f24f20c722f91663c85fbccbf7652622472012da19328a851585c6e1e59f263131c31a0eb9ff7d893fbf884f1ca9b169d5766fa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
